### ISSUE TITLE
Why is the C code required?

### ISSUE THREAD

**Issue by IainNZ** [zyedidia/SFML.jl#1]
Hey @zyedidia, I haven't done a deep dive into the code, but I was wondering why the C bindings are needed?

Looking forward to seeing a demo of a Julia-powered game at JuliaCon!

**Comment by zyedidia** [comment]
The C code is only required to support SFML events. Events in SFML are union types but passing union types between Julia and C is not currently supported, so the C code is necessary to pass the values through functions.

I'm glad to hear you're excited for my JuliaCon demo!
