### ISSUE TITLE
Any idea how to do transparent textures?

### ISSUE THREAD

**Issue by IainNZ** [zyedidia/SFML.jl#15]
I have some PNGs with some alpha=0 pixels, but unfortunately they're drawn with an opaque background. Any idea how to do it?

**Comment by IainNZ** [comment]
Maybe http://www.sfml-dev.org/documentation/2.0/classsf_1_1Image.php#a22f13f8c242a6b38eb73cc176b37ae34, but this isn't wrapped right now, right?

**Comment by zyedidia** [comment]
Are you using a sprite to draw the image? In the `image.jl` example, the image is transparent, but the background is white. If you change the last bit of the code in `image.jl` (the draw sequence), you can really see the transparency of the logo image:

```julia
# Clear the screen and redraw the sprite
clear(window, SFML.white)
draw(window, logo)
move(logo, Vector2f(-50, 10))
draw(window, logo)
move(logo, Vector2f(50, -10))
display(window)
```

**Comment by IainNZ** [comment]
I'm using a `set_texture` on a `RectangleShape()`, I'll try a `Sprite`

**Comment by IainNZ** [comment]
Oh man, RectangleShape works fine, its just that I wasn't drawing the background! Ignore me :+1: 

<img width="512" alt="screen shot 2015-11-23 at 1 17 45 pm" src="https://cloud.githubusercontent.com/assets/692635/11345383/9d2b2622-91e4-11e5-866d-674b1b7d3ad4.png">
