### ISSUE TITLE
Build fails on Linux Mint 17 (debian derivative)

### ISSUE THREAD

**Issue by explodingbat** [zyedidia/SFML.jl#8]
I installed libsfml-dev but it went in /usr/ , not /usr/local/

Also all the header files were .hpp not .h , i tried old versions of SFML from their site but they've been .hpp as far as version 1.6

    julia> Pkg.build("SFML")
    INFO: Building SFML
    Window/event.c:2:31: fatal error: SFML/Window/Event.h: No such file or directory
     #include <SFML/Window/Event.h>
                                   ^
    compilation terminated.
    Network/Network.c:2:26: fatal error: SFML/Network.h: No such file or directory
     #include <SFML/Network.h>
                              ^
    compilation terminated.
    Graphics/shader.c:2:27: fatal error: SFML/Graphics.h: No such file or directory
     #include <SFML/Graphics.h>
                               ^
    compilation terminated.
    ERROR: failed process: Process(`gcc -fPIC -I/home/oliver/.julia/v0.3/SFML/deps/csfml/include -c Window/event.c Network/Network.c Graphics/shader.c`, ProcessExited(1)) [1]
     in pipeline_error at process.jl:502
     in run at ./process.jl:479
     in include at ./boot.jl:245
     in include_from_node1 at loading.jl:128
     in process_options at ./client.jl:285
     in _start at ./client.jl:354
    while loading /home/oliver/.julia/v0.4/SFML/src/c/createlib.jl, in expression starting on line 9
    =============================================[ ERROR: SFML ]=============================================

**Comment by zyedidia** [comment]
Looks like the problem is that it is looking in the .julia/v0.3 instead of 0.4. I'll take a closer look later when I have time, but you might be able to figure it out now.

**Comment by explodingbat** [comment]
Arg! I'm very sorry for bothering you, hadn't installed v0.4 properly

**Comment by zyedidia** [comment]
No problem! I'm glad I could help.
